# config.yaml
# 프로젝트 주요 설정 파일

# 임베딩 모델 경로
embedding_model_path: './models/bge-small-en-v1.5'

# reranker 모델 경로
reranker_model_path: './models/cross-encoder-ms-marco-MiniLM-L6-en-de-v1'

# LLM 모델 경로
llm_model_path: './models/kullm-1-3b'

# ChromaDB 벡터 저장 경로
chroma_db_path: './db/'

# 검색 시 반환할 Top-K 문단 수
retriever_top_k: 10

# reranker 후 LLM에 넣을 문단 수
reranker_top_n: 3 